# Generated by Django 5.2 on 2025-05-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_info', '0004_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_exp',
        ),
    ]
