# Generated by Django 5.2 on 2025-05-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_info', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
