# Generated by Django 5.2 on 2025-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_info', '0008_alter_order_user_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowsorder',
            name='size',
            field=models.CharField(default='M', max_length=255),
        ),
    ]
