# Generated by Django 5.2 on 2025-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_info', '0010_remove_rowsorder_size_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowsorder',
            name='size',
            field=models.CharField(default='M', max_length=255),
        ),
    ]
