# Generated by Django 5.2 on 2025-06-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_info', '0011_rowsorder_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
